server:
  port: 8083
spring:
  datasource:
    url: jdbc:mysql://localhost:2013/TR?createDatabaseIfNotExist=true
    username: root
    password: password
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    open-in-view: false
